### ISSUE TITLE
AspirantProgram: Automated deployments to Ec2 Environment

### ISSUE THREAD

**Issue by meenatt** [MilsatLtd/AspirantProgram#13]
**Description**

update MAP to use automated deployments
```[tasklist]
### Tasks
- [x] Deploy api to Env
- [x] Deploy admin portal to Env
- [x] Deploy web-page to Env
- [x] Access all three apps via web browser
- [ ] Add environment variables
```
