### ISSUE TITLE
Setup Redis db for background job

### ISSUE THREAD

**Issue by dera-milsat** [MilsatLtd/AspirantProgram#25]
Setup Redis db on program server to run background jobs.
```[tasklist]
### Tasks
- [x] Setup Admin profile
- [x] Setup Redis db on instance
- [x] Setup db credentials
- [x] Setup .env file
- [x] Remove port 25 restriction on ec2 instance
```
